course_name = "控制理论中的代数基础"
course_code = "AUTO2006"

notices = """
2023 级，这门课与《电磁场》（2 学分）二选一[作为自动化与电气工程的分野]；2024 级，这门课与《固体力学》（3 学分）二选一[作为自动化与机器人工程的分野]。
"""

[[lecturers]]
name = "梅杰"
  [[lecturers.reviews]]
  content = """
  负责课程的前半部分，授课方式非常现代——在 iPad 上用 Goodnotes 书写板书并实时投屏👍
  课前会将用 LaTeX 制作的 PDF 讲义发放至课程群，课后会将手写讲义发放至课程群
  老师语速较快，知识密度高，上课可能跟不上，作业也比较难，但可以课后整理老师上课的笔记，这是期末复习的重要资料
  考勤形式是点名回答问题，所以上课不仅要去，还要认真听
  """
  author = { name = "", link = "", date = "" }

[[lecturers]]
name = "李衍杰"
  [[lecturers.reviews]]
  content = """
  负责课程的后半部分，授课采用 PPT + 板书的方式，课前会将 PPT 发放至课程群
  老师语速较慢，知识密度较低，拓展较多。作业比较简单，但可能不会完全覆盖考点，需要仔细看课件
  考勤形式是遍历型点名
  """
  author = { name = "", link = "", date = "" }

[[textbooks]]
title = "Linear Algebra Done Right"
book_author = "Sheldon Axler"
publisher = ""
edition = "3rd ed.(2015) / 4th ed.(2023)"
type = "reference"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2025-07-01" }

[[textbooks]]
title = "Introduction to Linear Algebra"
book_author = "Gilbert Strang"
publisher = ""
edition = "5th ed.(2016) / 6th ed.(2023)"
type = "reference"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2025-07-01" }

[[textbooks]]
title = "Linear Algebra and Its Applications"
book_author = "Lay D.C."
publisher = ""
edition = "5th ed."
type = "reference"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2025-07-01" }

[[textbooks]]
title = "Linear Algebra with Applications"
book_author = "Steven J. Leon"
publisher = ""
edition = ""
type = "reference"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2025-07-01" }

[[textbooks]]
title = "Linear Algebra Done Wrong"
book_author = "Sergei Treil"
publisher = "Brown University"
edition = ""
type = "reference"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2025-07-01" }

[[textbooks]]
title = "控制理论中的代数基础"
book_author = "季海波"
publisher = "中国科学技术大学"
edition = ""
type = "reference"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2025-07-01" }

[[textbooks]]
title = "系统与控制理论中的线性代数"
book_author = "黄琳"
publisher = "科学出版社"
edition = ""
type = "reference"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2025-07-01" }

online_resources = []

[[course]]
content = """
在自动控制专业中，线性代数或矩阵论是一个重要的数学基础。向量空间、线性映射等知识点是线性系统理论必不可少的预备知识。

本课程在线性代数的基础上进一步增加符合控制相关学科的代数基础内容，使学生获得代数的基本知识和基本理论，掌握必要的数学运算技能；
使学生进一步夯实代数基础和具备高维空间的代数描述和逻辑推理能力，同时使学生运用数学方法分析问题和解决问题的能力得到进一步的培养和锻炼，为后续课程的学习打好基础。
"""
author = { name = "教学大纲", link = "", date = "" }

[[exam]]
content = """
考试难度：中

题目包括但不限于：课本课后习题原题、作业题魔改、书本有关定理证明。

2025 春考试:
题型：15 个判断题 30 分，九道大题 70 分。大多为基础题、计算题，拔高的构造式证明题仅占 3 分。
但由于是考查课，作为助教，从平时作业就可看出同学们对于课程的态度总体不算认真。再加之备考时间紧张，许多同学复习并不充分，试卷上出现大片空白，最后成绩不理想。
希望同学们以思维锻炼的眼光看待这门课，活化自己的头脑。
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2025-07-01" }

lab = []

[[advice]]
content = """
推荐学习路线：

1. 个人建议在课程开始前（比如寒假的时间是最好的，这本书读起来也是很有趣的）阅读《线性代数及其应用》，这本书讲得比较浅显易懂。由于本书涉及了比较多的应用，过于专业的问题可以跳过，能够把这本书读完后基本能对线性代数有一个比较直观的认知。我强烈推荐至少要阅读前四章，因为国内的线性代数教材并不注重线性空间等知识，而是有大量的计算。而根据我上课来看，控代的老师似乎是默认你有一定的认识，然而我感觉大部分同学像是没有学习过线性代数一样。因此，推荐这本书作为真正的第一次学习线性代数。

2. 上课的时候也要认真听，毕竟题是由两位授课教师出的，但是有了前面的学习，相信你听起课来肯定会更加轻松，只需要注意一些细节的点。尤其是前半部分相对来说是一个比较新的部分，注意理解作业题的思路。如果自己第一次学好了线性代数，后半部分学习应该是比较轻松的。
"""
author = { name = "AutoFriedRich", link = "https://github.com/AutoFriedRich", date = "2024-05-01" }

[[advice]]
content = """
本课属于自动化的专业课，主要目标是补充学习线性代数中有关线性空间的知识。

这门课的意义在于大一上的 代数与几何 侧重于矩阵运算，而我们并没有学习这些算法该用在哪里；只有到了向量空间上，线性代数才是真正的线性代数，才能体现其在实际应用中的重要性。
所以除了授课语言外，本课程与 代数与几何 最重要的区别是“弱计算，重思想”。

课程使用英文 PPT，但是中文讲授；作业和考试要求用英语完成，因此对学生的英语水平有一定要求。
其实这个要求也高不到哪儿去，用一位学长的话说就是像编程语言一样，掌握一些常用的词汇术语，然后能够把它们组合起来就可以了。

教材没有硬性规定，学生一般用英文原版的 *Linear Algebra Done Right*，或者它的中译本《线性代数应该这样学》。

事实上整门课程的教学安排没有完全按照教材顺序，也没有覆盖 *Linear Algebra Done Right* 上的全部内容，课程架构与书还是存在一定出入的。

有的重点内容反而在书上没有，所以可以提前下载老师的讲义进行预习，甚至不依赖教材。

最后吐槽一下：国内的课本是真的一坨
"""
author = { name = "Maxwell Jay 和 longlin li", link = "https://github.com/MaxwellJay256, https://github.com/longlin10086", date = "2023-06-01" }

[[advice]]
content = "要认真看课件上的例题和作业题。"
author = { name = "", link = "", date = "" }

[[advice]]
content = "期末最后一节课或者考试前夕，老师会安排答疑和作业评讲课，至于课上会讲什么，懂得都懂，所以 梅老师的期末答疑课一定要去听。"
author = { name = "", link = "", date = "" }

[[schedule]]
content = """
梅老师负责部分（24 学时）
Lec 1、Lec 2: 绪论（课程目的及主要内容） 线性空间的概念
Lec 2: 子空间
Lec 2: 线性相关、基和维数
Lec 2: 基变换
Lec 2: 矩阵的四个子空间
Lec 2: 四个子空间之间的正交关系
以上主要对应《线性代数应该这样学》前两章，矩阵的四个子空间的部分可以看 Gilbert Strang 老爷子的书和网课。

Lec 3: 线性变换的定义、零空间和值域、单射和满射
Lec 3: 线性变换的基本定理、线性变换的矩阵表示
Lec 3: 图像的扭曲和变形、投影与最小二乘
Lec 3: 线性变换的代数运算、可逆与同构
Lec 3: 向量空间的积和商
Lec 4: 线性方程组的数值求解、数值逼近
上半程课程回顾
以上主要对应《线性代数应该这样学》第三章，有关矩阵表示的部分可以看 Lay D.C., Linear Algebra and Its Applications, 5th ed.（见校内网盘）。数值求解部分主要看讲义，也可以看数值分析课程仓库（也不作为考试内容）。

李老师负责部分（24 学时）
Lec 5: 内积空间和正交
Lec 5: 内积范数和一般范数
Lec 5: 正交基和标准正交基
Lec 5: 线性泛函和表示定理
Lec 5: 正交补及其性质
Lec 5: 正交投影及其性质
Lec 5: 最小二乘
Lec 6: 线性映射的不变子空间与特征向量
Lec 6: 特征值的存在性和上三角矩阵表示
Lec 6: 线性映射的对角化
Lec 6: 线性微分方程组求解
Lec 6: 奇异值分解
后半程课程回顾
以上主要对应《线性代数应该这样学》第五、六章。
"""
author = { name = "", link = "", date = "" }

[[related_links]]
content = "Solutions to Linear Algebra Done Right (第 3 版习题解答)😏: https://linearalgebras.com/"
author = { name = "", link = "", date = "" }

[[related_links]]
content = "The Art of Linear Algebra (含中译，线性代数知识可视化): https://github.com/kenjihiranabe/The-Art-of-Linear-Algebra"
author = { name = "", link = "", date = "" }

[[related_links]]
content = "类似 StackOverflow 的数学论坛: https://math.stackexchange.com/"
author = { name = "", link = "", date = "" }

[[related_links]]
content = "kumiko - 线性代数应该这样学 // Linear Algebra Done Right （自学用）- Bilibili: https://www.bilibili.com/video/BV1uK4y1a7jL"
author = { name = "", link = "", date = "" }

[[misc]]
content = "CASIO fx-991 X 计算器可以进行矩阵运算。"
author = { name = "", link = "", date = "" }

[[misc]]
content = """
关于教材与参考书的补充说明：
老师自编的讲义会参考以下 4 本教材，参考程度从上到下递减。阅读原书、建立完整的知识体系大有裨益，不过限于时间，可以选择性阅读。
《Linear Algebra Done Right》的官方网站：linear.axler.net，提供免费电子书。2023 年作者发布了第 4 版。第 4 版中译由哈深 21 级的两位学生完成，已发布。
《Introduction to Linear Algebra》有对应网课：B 站搜 Gilbert Strang 即可。
《Introduction to Linear Algebra》, 《Linear Algebra and Its Applications》, 《Linear Algebra with Applications》这 3 本电子书可在校内网盘（MATH1002 或 AUTO2006 文件夹）下载。
《Linear Algebra Done Wrong》在矩阵与线性映射的关系上讲解比 Lay 更为简洁且不失严谨；对于行列式有非常简洁但富有动机的讲法；后续更进阶的内容也写得很简洁清晰。值得一读。
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2025-07-01" }