course_name = "控制理论中的代数基础"
repo_type = "normal"
course_code = "AUTO2006"

description = """
2023 级，这门课与《电磁场》（2 学分）二选一[作为自动化与电气工程的分野]；2024 级，这门课与《固体力学》（3 学分）二选一[作为自动化与机器人工程的分野]。

本课程在线性代数的基础上进一步增加符合控制相关学科的代数基础内容，重点在于向量空间、线性映射等知识点。
"""

[[lecturers]]
name = "梅杰"

[[lecturers.reviews]]
content = """
负责课程的前半部分。
授课方式非常现代——在 iPad 上用 Goodnotes 书写板书并实时投屏。
课前会将用 LaTeX 制作的 PDF 讲义发放至课程群，课后会将手写讲义发放至课程群。
老师语速较快，知识密度高，上课可能跟不上，作业也比较难，但可以课后整理老师上课的笔记，这是期末复习的重要资料。
考勤形式是点名回答问题，所以上课不仅要去，还要认真听。
"""

[[lecturers]]
name = "李衍杰"

[[lecturers.reviews]]
content = """
负责课程的后半部分。
授课采用 PPT + 板书的方式，课前会将 PPT 发放至课程群。
老师语速较慢，知识密度较低，拓展较多。作业比较简单，但可能不会完全覆盖考点，需要仔细看课件。
考勤形式是遍历型点名。
"""


[[sections]]
title = "教材"

[[sections.items]]
content = """
- **Linear Algebra Done Right**（Sheldon Axler / Springer / 3rd ed.(2015) / 4th ed.(2023) / textbook）
- **Introduction to Linear Algebra**（Gilbert Strang / Wellesley-Cambridge Press / 5th ed.(2016) / 6th ed.(2023) / textbook）
- **Linear Algebra and Its Applications**（Lay D.C. / Pearson / 5th ed. / textbook）
- **Linear Algebra with Applications**（Steven J. Leon / Pearson / textbook）
- **Linear Algebra Done Wrong**（Sergei Treil / Brown University / textbook）
- **控制理论中的代数基础**（季海波 / 中国科学技术大学 / textbook）
- **系统与控制理论中的线性代数**（黄琳 / 科学出版社 / textbook）
"""


[[sections]]
title = "在线资源"

[[sections.items]]
content = """
- [linear.axler.net](https://linear.axler.net/)：Linear Algebra Done Right 官方网站，提供免费电子书
- [Solutions to Linear Algebra Done Right](https://linearalgebras.com/)：第 3 版习题解答
- [The Art of Linear Algebra](https://github.com/kenjihiranabe/The-Art-of-Linear-Algebra)：线性代数知识可视化，含中译
- [Math StackExchange](https://math.stackexchange.com/)：类似 StackOverflow 的数学论坛
- [线性代数应该这样学 (Bilibili)](https://www.bilibili.com/video/BV1uK4y1a7jL)：kumiko 上传的自学视频
"""


[[sections]]
title = "课程内容"

[[sections.items]]
content = """
### 梅老师负责部分（24 学时）

| 对应讲义 | 教学内容 | 教学要求 | 学时 |
| :--- | :--- | :--- | :--- |
| Lec 1、Lec 2 | 绪论（课程目的及主要内容） 线性空间的概念 | 1.了解本课程研究的对象、内容； 2.掌握线性空间基本概念和八大公理。 | 2 |
| Lec 2 | 子空间 | 1.掌握子空间、子空间的和与直和，以及生成空间的概念 | 1 |
| Lec 2 | 线性相关、基和维数 | 1.掌握线性相关（无关）的概念及性质、基和维数的定义 | 2 |
| Lec 2 | 基变换 | 1.掌握基变换的定义 2.掌握**转移矩阵的计算方法** 3.了解如何用基变换来进行图像压缩 | 2 |
| Lec 2 | 矩阵的四个子空间 | 1. 掌握矩阵**四个子空间的定义和计算方法**：列空间、行空间、零空间、左零空间 2. 掌握线性代数基本定理I：理解各子空间之间的维数关系 | 2 |
| Lec 2 | 四个子空间之间的正交关系 | 1. 掌握向量和空间正交的定义 2. 掌握线性代数基本定理II：理解各子空间之间的正交关系 | 1 |
| Lec 3 | 线性变换的定义、零空间和值域、单射和满射 | 1. 掌握线性变换、零空间和值域、单射和满射及其性质 2. 掌握相关计算方法 | 2 |
| Lec 3 | 线性变换的基本定理、线性变换的矩阵表示 | 1.理解**线性变换的基本定理**，掌握线性变换基本定理的**证明思路** 2.掌握**线性矩阵表示的定义和相关计算方法** 3.了解等价矩阵和相似矩阵的定义 | 2 |
| Lec 3 | 图像的扭曲和变形、投影与最小二乘 | 1.了解如何用线性变换来完成图像的扭曲和变形 2.掌握投影算法与最小二乘问题 | 2 |
| Lec 3 | 线性变换的代数运算、可逆与同构 | 1. 从线性变换矩阵表示的角度理解矩阵运算的本质 2. 掌握可逆矩阵和同构的概念；3. 掌握**构造线性映射的方法**；4. 理解任意有限维向量空间与 $\\mathbb{F}^n$ 的同构、矩阵与线性映射的同构 | 2 |
| Lec 3 | 向量空间的积和商 | 1. 了解向量空间的积；2. 了解平移、商空间、商映射 | 2 |
| Lec 4 | 线性方程组的数值求解、数值逼近 | 1. 了解线性方程组的数值求解方法、了解逼近插值的相关方法 | 3 |
| | 上半程课程回顾 | | 1 |

### 李老师负责部分（24 学时）

| 对应讲义 | 教学内容 | 教学要求 |
| :--- | :--- | :--- |
| Lec 5 | 内积空间和正交 | 1.掌握内积空间和正交概念 2.掌握内积范数的一些不等式 |
| Lec 5 | 内积范数和一般范数 | 1.掌握内积与一般范数的区别 2.理解1范数与稀疏性 |
| Lec 5 | 正交基和标准正交基 | 1.掌握正交基和标准正交基 2.掌握**施密特正交化过程** |
| Lec 5 | 线性泛函和表示定理 | 1.掌握线性泛函的概念 2.理解Riesz表示定理 |
| Lec 5 | 正交补及其性质 | 1.掌握正交补的相关概念 2.理解正交补的性质 |
| Lec 5 | 正交投影及其性质 | 1.掌握正交投影的概念 2.掌握**正交投影计算和投影矩阵** |
| Lec 5 | 最小二乘 | 1.掌握**最小二乘**概念 2.掌握最小二乘和正交投影关系 |
| Lec 6 | 线性映射的不变子空间与特征向量 | 1.掌握不变子空间的概念 2.掌握线性映射的特征向量概念 |
| Lec 6 | 特征值的存在性和上三角矩阵表示 | 1.理解特征值的存在性 2.掌握上三角矩阵表示的性质 |
| Lec 6 | 线性映射的对角化 | 1.掌握可**对角化**矩阵表示的条件及方法 |
| Lec 6 | 线性微分方程组求解 | 1.掌握**线性一阶、二阶微分方程组的求解** |
| Lec 6 | 奇异值分解 | 1.掌握**奇异值分解的求解方法** |
| | 后半程课程回顾 | |
"""


[[sections]]
title = "关于考试"

[[sections.items]]
content = """
**2025 春考试情况：**

- **考试难度**：中。
- **题型**：15 个判断题 30 分，九道大题 70 分。题目包括但不限于：课本课后习题原题、作业题魔改、书本有关定理证明。
- **内容**：大多为基础题、计算题，拔高的构造式证明题仅占 3 分。
- **总结**：由于是考查课，同学态度总体不算认真，复习不充分导致成绩不理想。希望同学们以思维锻炼的眼光看待这门课。
"""


[[sections]]
title = "学习建议"

[[sections.items]]
content = """
1. **预习建议**：建议在课程开始前（如寒假）阅读《线性代数及其应用》(Lay D.C.) 的前四章。这本书比较浅显易懂，适合建立直观认知。国内教材通常计算较多，不注重线性空间，因此推荐以此书作为真正的第一次学习。
2. **上课建议**：前半部分相对较新，需注意理解作业题思路。如果预习好了，后半部分学习会比较轻松。
"""

[[sections.items]]
content = """
本课侧重于**线性空间**的知识，与大一的代数与几何（重矩阵运算）不同，强调“弱计算，重思想”。
课程使用**英文 PPT**，中文讲授；作业和考试要求用英语完成，对英语水平有一定要求（掌握常用词汇术语即可）。
课程架构与 *Linear Algebra Done Right* 不完全一致，有的重点内容书上没有，建议提前下载老师讲义预习。
"""


[[sections]]
title = "其他注意事项"

[[sections.items]]
content = """
- 期末最后一节课或者考试前夕，老师会安排答疑和作业评讲课，**梅老师的期末答疑课一定要去听**。
- CASIO fx-991 X 计算器可以进行矩阵运算。
"""
